language: java
jdk:
  - oraclejdk8
before_script: |
  if ([ $TRAVIS_PULL_REQUEST = "false" ] && [ $TRAVIS_BRANCH = "master" ]); then
    ./make_credentials.py
  fi

script: 
  - find $HOME/.m2 -name "_remote.repositories" | xargs rm
  - find $HOME/.m2 -name "resolver-status.properties" | xargs rm -f
  
# If building master, Publish to Sonatype
after_success: |
  if ([ $TRAVIS_PULL_REQUEST = "false" ] && [ $TRAVIS_BRANCH = "master" ]); then
    mvn deploy
  fi

sudo: false

# https://github.com/travis-ci/travis-ci/issues/3259
addons:
  apt:
    packages:
      - oracle-java8-installer

# Cache settings
cache:
  directories:
    - $HOME/.m2/repository
